### ISSUE TITLE
Error creating temporary layer

### ISSUE THREAD

**Issue by r-geoman** [YoannQDQ/qgis-layer-tree-icons#14]
I used the buffer tool on a line object, a new layer “buffered” was created and immediately an error:

```
2024-02-28T01:43:33     WARNING    Traceback (most recent call last):
              File "C:\Users/Rain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layertreeicons\customtreemodel.py", line 151, in data
              layer = node.layer()
             AttributeError: 'QgsLayerTreeNode' object has no attribute 'layer'
             
2024-02-28T01:43:33     WARNING    Traceback (most recent call last):
              File "C:\Users/Rain/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layertreeicons\customtreemodel.py", line 208, in data
              layer = node.layer()
             AttributeError: 'QgsLayerTreeNode' object has no attribute 'layer'
```

from version 3.18 to version 3.36 I am waiting for a solution to this problem or I am waiting for you to update the module.
Help me solve this problem, please!

```
Python Stack Trace
Windows fatal exception: access violation
Current thread 0x00009ab0 (most recent call first):
Stack Trace
QRasterPaintEngine::brushChanged :
QgsLayerTreeViewIndicator::QgsLayerTreeViewIndicator :
QTreeView::drawRow :
QTreeView::drawTree :
QTreeView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QMessageBox::showEvent :
QMessageBox::warning :
QgisApp::removeLayer :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.36.0-Maidenhead
QGIS code revision: 09951dc0
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4
System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
```

![28-02-2024 02-02-48](https://github.com/YoannQDQ/qgis-layer-tree-icons/assets/135266467/f3e80133-e6a0-4c1c-8de7-49642f6f8f0a)

![28-02-2024 02-03-00](https://github.com/YoannQDQ/qgis-layer-tree-icons/assets/135266467/0828282c-9b40-437b-b18d-14faf4d64b1b)

![28-02-2024 02-07-42](https://github.com/YoannQDQ/qgis-layer-tree-icons/assets/135266467/b9fdeb95-810a-4f6a-948a-3cd1fe0ab0b2)

**Comment by Alexander-Orlovsky** [comment]
It is a wary pity that this problem does not allow me and my many students to use the wonderful and fantastic plugin "Layer Tree Icons" with versions of QGIS newer than 3.16.  
   The plugin you created enormously improve the QGIS interface, making working in the program much more convenient, advanced and enjoyable.
