### ISSUE TITLE
Python error with the last version of the plugin

### ISSUE THREAD

**Issue by francis33** [YoannQDQ/qgis-layer-tree-icons#2]
Hello,

Thanks for including the possibility to use the opacity sliders in the last release of your plugin.
It's works correctly but I get systematiclaly this python error message : 

_2020-08-24T14:05:47     WARNING    Traceback (most recent call last):
              File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layertreeicons\customtreemodel.py", line 266, in data
              pixmap = pixmapForLegendNode(legend_node)
              File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layertreeicons\customtreemodel.py", line 170, in pixmapForLegendNode
              for l_node in model.layerLegendNodes(legend_node.layerNode())
              File "C:/Users/Cascade Interchange/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\layertreeicons\customtreemodel.py", line 170, in 
              for l_node in model.layerLegendNodes(legend_node.layerNode())
             AttributeError: 'QgsLayerTreeModelLegendNode' object has no attribute 'minimumIconSize'_

The message appears : 

- at the lauching of QGIS
- each time i click on an item of the layer tree

Is it a bug ? Or an issue of my computer ?

Thanks a lot.
Francis

**Comment by YoannQDQ** [comment]
The bug occured when one used an opacity slider on a vector layer with a sublegend. The plugin iterates on the child legend nodes to compute the minimum required width (useful when the textOnSymbol option is enabled), but the opacity slider node has no minimumIconSize, hence the exception.

The opacity slider node is now ignored for the minimum width computation.
Fixed in version 1.3.1. I just uploaded it on QGIS plugin, it should soon be approved.
